"""
09_train_style — style-conditioning adapter (Phase B3, optional).

Pipeline position: M8 — Training, phase B3 (optional, does not block completion)
Depends on: models/ftpo_model/ (M7), conditioned training pairs (curated separately)
Produces:   models/style_lora/, reports/style_eval.json

Adds a LoRA adapter on top of the M7 model that bends the editing output toward a target
author's voice when given a 3-5 paragraph style reference in the user turn. Without a style
reference, the model behaves identically to the base M7 editor (the adapter is a pure
extension, not a replacement).

This module is optional: the base editor (M6+M7) is a complete, usable product without it.
M8 should only be started after M7's gate checks pass and the base editor is stable.

HOW STYLE CONDITIONING WORKS
The STYLE_USER_TEMPLATE in prompt_config.py wraps the style reference in <style_reference>
tags and prepends it to the standard editing prompt. The model sees this tag structure in
conditioned training examples and learns to adapt its output register, sentence rhythm, and
vocabulary toward the reference while still removing slop and preserving content.

TRAINING REGIME
  - Rank 16 (not 32): the style signal is weaker than the editing signal; smaller adapter.
  - LR 5e-5 (same as FTPO): conservative to avoid overwriting M6/M7 behaviour.
  - 2 epochs maximum: style generalisation needs variety, not repetition; more epochs risks
    overfitting to specific reference authors.
  - Train ONLY on conditioned pairs (style reference included in every example). Do not mix
    with unconditioned M6/M7 pairs. Mixing causes the adapter to partially suppress the base
    editing capability when no style reference is present.

GATE (must pass before declaring M8 done):
  - No regression on ner_preservation, sem_vs_target, slop_delta vs. ftpo_eval.json baseline.
  - Conditioned outputs measurably shift toward the reference style (measured by a style
    similarity metric — cosine similarity between output and reference embeddings is a
    reasonable proxy).

Usage:
    python scripts/09_train_style.py [--base models/ftpo_model]
                                     [--pairs data/style_pairs.jsonl]
                                     [--output models/style_lora]
    # then evaluate:
    python scripts/run_eval.py models/style_lora reports/style_eval.json

Key implementation notes:
  - Conditioned training pairs (data/style_pairs.jsonl) must be curated separately — not
    generated by the M4 pipeline. Each pair needs a matching style reference excerpt from the
    same author as the clean target.
  - The STYLE_USER_TEMPLATE and STYLE_SYSTEM_PROMPT from prompt_config.py handle the
    message construction. Call build_messages(sloppy, clean, style_reference=...) for each pair.
  - Use the same DataCollatorForCompletionOnlyLM + RESPONSE_TEMPLATE setup as M6 to ensure
    completion-only loss masking. The same silent failure (model copies input) applies here.
"""

from pathlib import Path


def main(base_model="models/ftpo_model", pairs_path="data/style_pairs.jsonl",
         output_dir="models/style_lora"):
    """Train the style-conditioning adapter on top of the M7 FTPO model."""
    raise NotImplementedError


if __name__ == "__main__":
    main()
