"""
run_adversarial — run purpose-built adversarial tests against specific editor failure modes.

Pipeline position: M9 — Evaluation harness (complement to run_eval.py)
Depends on: data/eval_clean_prose.jsonl, data/eval_strong_voice.jsonl, data/eval_tone_tagged.jsonl
Produces:   reports/adversarial_<model_name>.json

Where run_eval.py measures aggregate behaviour on the test set, run_adversarial.py probes
specific failure modes with inputs designed to trigger them. Proxies confirm the model does
the right thing on average; adversarial tests confirm it isn't doing specific wrong things.

THE FOUR ADVERSARIAL TESTS

1. OVER-EDIT (eval_clean_prose.jsonl)
   Input: already-clean human prose (no slop). Expected: the model barely changes anything.
   Metric: mean semantic similarity between input and output should be >= 0.97.
   Failure means: the null-edit pairs in M5 were insufficient. Fix: raise M5 null fraction.

2. VOICE-FLATTENING (eval_strong_voice.jsonl)
   Input: excerpts with a strong, idiosyncratic narrator voice (e.g. unreliable narrator,
   stream of consciousness, heavy dialect). Expected: the narrator's profile is preserved.
   Metric: stylometric cosine similarity between input and output should stay >= 0.85.
   Failure means: the model is homogenising prose toward a "neutral" style.

3. TONE-PRESERVATION (eval_tone_tagged.jsonl)
   Input: excerpts tagged with a tone label ({"text": "...", "tone": "darkly comic"}).
   Expected: the tone label is preserved after editing.
   Metric: LLM judge (or manual) agreement that the edited text retains the stated tone.
   Failure means: the model is altering the emotional register of the prose.

4. HALLUCINATION (reuses eval_clean_prose.jsonl)
   Input: clean prose with a known set of named entities.
   Expected: no new named entities appear in the output.
   Metric: hallucination_rate from eval_metrics should be < 0.03 on clean input.
   Failure means: the model is inventing content even when the input needs no editing.

FIXTURE FILES
  data/eval_clean_prose.jsonl    — {"text": str}  (slop-free human excerpts)
  data/eval_strong_voice.jsonl   — {"text": str}  (idiosyncratic narrators)
  data/eval_tone_tagged.jsonl    — {"text": str, "tone": str}
These must be hand-curated (not generated by the pipeline). 20-30 items per fixture is
sufficient for meaningful signal; more is better for the tone test which has high variance.

Usage:
    python scripts/run_adversarial.py <model_dir> [--report reports/adversarial_sft.json]

Key implementation notes:
  - The over-edit and hallucination tests can use eval_metrics.sem_sim and
    eval_metrics.hallucination_rate directly — no new metric code needed.
  - The tone test has high variance with a single LLM judge call. Average 3+ calls or use
    human annotation for the tone fixture if the verdict flips on re-run.
  - Voice-flattening uses stylometric cosine similarity — embed the input and output with
    the same sentence-transformer as eval_metrics.py and compare. A large drop in similarity
    (delta > 0.15) flags flattening even without a reference author embedding.
"""

import json
import sys
from pathlib import Path
from scripts.eval_metrics import sem_sim, hallucination_rate


def over_edit_score(model_edit_fn, fixture_path="data/eval_clean_prose.jsonl"):
    """Mean semantic similarity between input and model output on clean prose.

    model_edit_fn: callable(sloppy_text: str) -> edited_text: str
    A score >= 0.97 indicates the model is not over-editing clean input.
    """
    raise NotImplementedError


def hallucination_on_clean(model_edit_fn, fixture_path="data/eval_clean_prose.jsonl"):
    """Mean hallucination_rate on clean prose (expect < 0.03)."""
    raise NotImplementedError


def voice_flattening_score(model_edit_fn, fixture_path="data/eval_strong_voice.jsonl"):
    """Mean stylometric cosine similarity input→output on strong-voice excerpts (expect >= 0.85)."""
    raise NotImplementedError


def tone_preservation_score(model_edit_fn, judge_fn, fixture_path="data/eval_tone_tagged.jsonl"):
    """Fraction of tone-tagged excerpts where the tone is judged preserved after editing.

    judge_fn: callable(text: str, tone: str) -> bool  (LLM judge or human annotation)
    """
    raise NotImplementedError


def main(model_dir=None, report_path=None):
    """Run all adversarial tests and write the summary report."""
    raise NotImplementedError


if __name__ == "__main__":
    main()
